# Generated by Django 3.0.8 on 2020-08-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pswrd', models.CharField(max_length=60)),
                ('pswrdcheck', models.CharField(max_length=60)),
            ],
        ),
    ]
