# Generated by Django 3.0.8 on 2020-08-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20200815_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='fooditems',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('id', models.IntegerField(default='defaultid()', primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='regdata',
            name='pswrdcheck',
        ),
        migrations.AddField(
            model_name='regdata',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regdata',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
