# Generated by Django 3.0.8 on 2020-08-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_auto_20200816_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fooditems',
            new_name='fooditem',
        ),
    ]
