# Generated by Django 3.0.8 on 2020-08-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_auto_20200816_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
