# Generated by Django 3.0.8 on 2020-08-16 20:13

from django.db import migrations

def statepop(apps,schema_editor):

    state = apps.get_model('foodapp', 'state')
    Totalstates="Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chhattisgarh,Goa,Gujarat,Haryana,Himachal Pradesh,Jammu and Kashmir,Jharkhand,Karnataka,Kerala,Madhya Pradesh,Maharashtra,Manipur,Meghalaya,Mizoram,Nagaland,Odisha,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,Uttar Pradesh,Uttarakhand,West Bengal,Andaman and Nicobar,Chandigarh,Dadra and Nagar Haveli,Daman and Diu,Lakshadweep,Delhi,Puducherry"
    statename=''

    for i in Totalstates:
        if i != ',':
            statename+=i
        else:
            istate=state()
            istate.state=statename
            istate.save()
            statename=''

    istate.state=statename
    istate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_auto_20200816_2358'),
    ]

    operations = [migrations.RunPython(statepop)
    ]
