# Generated by Django 3.0.8 on 2020-08-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0011_remove_fooditem_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='percentdisc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
