# Generated by Django 3.0.8 on 2020-08-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0012_auto_20200817_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='img',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
