# Generated by Django 3.0.8 on 2020-08-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0014_indvdl_order_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_active',
            field=models.BooleanField(default=False),
        ),
    ]
